CREATE TABLE TEST_DB (
    id SERIAL PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)

INSERT INTO TEST_DB(title) VALUES ('test text 1')

INSERT INTO TEST_DB(title) VALUES ('test text 2')


SELECT * FROM TEST_DB